### ISSUE TITLE
Why $params are not part of $app['config']? 

### ISSUE THREAD

**Issue by Shaked** [lokhman/silex-config#2]
Hey, 

I might have understood this a bit wrong, but why did you choose to copy `"$params"` to `$app` and not to `$app['config']`?

For example:
```
$app->register(new ConfigServiceProvider(), [
    'config.dir'    => __DIR__ . '/../config',
    'config.env'    => $env,
    'config.params' => [
        'custom' => "this is a test",
    ],
]);
assert($app['custom'] == "this is a test"); // true  
assert($app['config']['custom'] == "this is a test"); // false
```

In general this means that any existing key in the container cannot be used in the config and vice versa, depending who is being registered first. For example:
```
default.json
{
"monolog": {
    "level": "DEBUG"
}
}

$app->register(new ConfigServiceProvider(), [
    'config.dir'    => __DIR__ . '/../config',
    'config.env'    => $env,
]);

$app['monolog'] = $app->register(new \Silex\Provider\MonologServiceProvider(), $app['config']);
```
This will throw an exception "monolog" is frozen as it is already registered by the configuration provider and cannot be registered again to `$app['monolog']` which represents the logger. 

-- 
Regardless, the documentation states the following: 

> By default, service provider embeds tokens __DIR__ and __ENV__, as well as all PHP environment variables (e.g. REMOTE_ADDR, SERVER_NAME, etc).

Do I have to register all the `$_SERVER` variables or they are supposed to be copied in the provider? I couldn't find it and this would be great to have built in. 

Thank you for the great stuff, 
I am happy to contribute if what I wrote above make sense for you :) 
Shaked

**Comment by lokhman** [comment]
First of all thank you for raising the issue, I really appreciate that you are interested in this library ;)

On the point, in your example you are registering `MonologServiceProvider` in a bit wrong way. What is really good with `ConfigServiceProvider` is that you don't need to pass its registered instance to every other provider. Just do the following:

    $app->register(new ConfigServiceProvider(), [
        'config.dir' => __DIR__ . '/../config',
    ]);

    $app->register(new MonologServiceProvider());

And `Monolog` will be automatically registered to `$app['monolog']`. All configuration parameters you can define in JSON config file under `"monolog. ..."` setting, e.g. `"monolog.logfile": "php://stderr"`.

Parameter `config.params` is required if you wish to pass additional parameters to `ConfigServiceProvider` to add them to `"$params"` property. I don't really use this setting in real life but someone may find it useful.

Regarding the environment variables, you don't need to copy them anyhow, If the variable exists, its token will be automatically replaced in the configuration, e.g. `"ip": "%REMOTE_ADDR%"`.

I hope it helps ;)

**Comment by Shaked** [comment]
@lokhman 

Thank you for the reply. 

Actually after using the package a bit I totally got the point of having everything being copied outside the `$app['config']`. The only thing is that I have more than 1 `monolog` log file so that's why I pass the parameter and create my own `monolog` loggers. 

Regarding the `$params`. This is a great feature actually which helps me a lot. The only thing is that after registering `ConfigServiceProvider` it is recommended to run `$app->boot` so that all the other dependencies will have the parsed `$params`. 

Thank you :)
Shaked
